### ISSUE TITLE
There are some new translations in translation.py

### ISSUE THREAD

**Issue by cangerjun** [quasar098/midi-playground#134]
@lucmsilva651 @leo539 @SpeckyYT @Guavvva @slideglide There are some new translations in translation.py 
——————————————————————————————————————
@suzuuuuu09 こにちわ！鈴ちゃん！
translations.pyにはいくつかの新しい翻訳があります。
私はあなたの代わりに追加しました。
中国語を参照して行われた翻訳は、必ずしも正確ではありません。
by：bilibili苍二君

**Comment by lucmsilva651** [comment]
I will take a time to pick the new strings and translate them soon. Ty for noticing us. ;)

**Comment by cangerjun** [comment]
I have a question to consult with friends from different countries
I will share this project with netizens in my country. They often encounter the problem of not being able to install dependencies and start. I wonder if netizens in your country have the same problem?
I have created two. bat files, please test them. I would like to hear different people's thoughts.:)
[bat.zip](https://github.com/user-attachments/files/16716131/bat.zip)

**Comment by lucmsilva651** [comment]
> I have a question to consult with friends from different countries I will share this project with netizens in my country. They often encounter the problem of not being able to install dependencies and start. I wonder if netizens in your country have the same problem? I have created two. bat files, please test them. I would like to hear different people's thoughts.:) [bat.zip](https://github.com/user-attachments/files/16716131/bat.zip)

You certainly didn't installed the dependencies with `pip install -r requirements.txt` and `pip install .`. And for compiling, there is a lot of things you will need to do if you are on Windows, since PyInstaller is different on every platform it runs. At least on my builds of the project, it taked me a long time to figure out how to compile everything.

But anyways, if you want to someone to test it out, you can share the stable releases out here.

**Comment by suzuuuuu09** [comment]
Hello! Thanks for helping me translate the Japanese!  
It might be easier to understand if you translate the settings section as follows.

```python
"do-custom-pgui-font": True,
"camera-mode": "カメラのモード",
"rng-seed": "乱数の初期値",
"starting-time-delay": "ゲーム開始時の遅延",
"max-notes-to-generate": "生成するノーツの最大数",
"bounce-min-spacing": "バウンドの最小間隔",
"square-speed": "ブロックの速度",
"music-offset": "音楽のオフセット",
"change-dir-chance": "方向転換の確率",
"hp-drain-rate": "HPの減少率",
"music-volume": "音楽の音量",
"color-theme": "カラーテーマ",
"theatre-mode": "シアターモード",
"particle-trail": "移動のエフェクト",
"shader": "シェーダー",
"color-pegs-on-bounce": "バウンド時のカラー表示",
"particles-on-bounce": "バウンド時のエフェクト表示",
"resolution": "解像度",
```

While working on this I found a mistake in the translation I did earlier, lol.  
I hope you can correct the next part as well!

```python
"title-marquee": f"""貢献者: {contributors}. ブロックを見ているだけじゃつまらないからゲームをプレイしてみたい？設定でシアターモードをオンにしてみてください。自分の曲を演奏したいけどやり方がわからない？ソースコードのdocs/SONGS.mdを見れば、自分の曲を追加する方法が分かります。""".replace(
            "\n", ''),

```

**Comment by quasar098** [comment]
i think it will make a new release soon with these included

**Comment by quasar098** [comment]
added them all

**Comment by giovannigsilva** [comment]
I'm having fun with your game, congratulations on the project!!!
Can you tell me more or less how I change the style of the square? like, put it in neon color, adjust the edges... I don't know if there is css in python but I'd like to try my hand at Python

**Comment by quasar098** [comment]
ok

**Comment by quasar098** [comment]
> I'm having fun with your game, congratulations on the project!!! Can you tell me more or less how I change the style of the square? like, put it in neon color, adjust the edges... I don't know if there is css in python but I'd like to try my hand at Python
@giovannigsilva 

you can probably write some code to change the rendering

the source code version does allow for glow (the exe version does not because the glow library does not cooperate with the exe version). this is named glowing3, i believe, you can just search for that and find related code. idk how to do rounded corners, but i think there are things in pygame that will allow you to do that

ok yeah here

![image](https://github.com/user-attachments/assets/bd38310c-7d88-4044-9e37-f45428bf9895)
