### ISSUE TITLE
Crashes on some MIDIs

### ISSUE THREAD

**Issue by gamecube-github** [quasar098/midi-playground#30]
When playing some MIDIs on laptops (like Rush E or custom Rush E Playable) the loading screen can:

1. be stuck (not-responding)
2. just don't load, seems like stuck but it is responding

The №1 can also give an error after couple of minutes like this:

> Traceback (most recent call last):
>   File "main.py", line 135, in <module>
>   File "main.py", line 105, in main
>   File "game.py", line 60, in start_song
>   File "world.py", line 162, in gen_future_bounces
> AssertionError: recurs function failed

What should I do?

**Comment by quasar098** [comment]
the recursion function generates the map, and sometimes there are bugs and the recursion function is a steaming pile of hot garbage anyways so i was thinking of redoing it, but i am quite busy right now give me like 3-5 business days

**Comment by quasar098** [comment]
sorry i forgot that this project exist, was busy with ctf and other projects, will get to it now

**Comment by quasar098** [comment]
one of the issues is that the stack (maybe the heap actually? idk) of the python program exceeds two gigabytes, and so the program randomly crashes without any error message. i think this is fixable by changing the square path to be external to the recursion function so it is O(n) space complexity rather than O(n^2) space complexity
