### ISSUE TITLE
请求添加新功能(Request new features to be added)

### ISSUE THREAD

**Issue by it7007** [quasar098/midi-playground#35]
1.屏幕录制：添加配置项，在游戏运行时，出发屏幕录制，在游戏退出时，结束录制，最终以时间戳命名输出到outFile文件夹。
2.调整方格大小：添加配置项，可以直接调整方格大小。
3.可以选择是否显示方格运动时周围的动画效果

1. Screen recording: Add a configuration item to start screen recording when the game is running, end the recording when the game exits, and finally output it to the outFile folder named with a timestamp.
2. Adjust the grid size: Add configuration items to directly adjust the grid size.
3. You can choose whether to display the surrounding animation effects when the square is moving

谢谢你，Thanks~!

**Comment by quasar098** [comment]
好主意，我正在考虑使用 ffmpeg 通过捕获帧来做到这一点。 然而，我没有动力或时间来制作这个功能，因为它很复杂，所以需要一些时间来开发。

good idea, i was thinking of using the ffmpeg to do that by capturing frames. however, i do not have the motivation or time to make this feature, because it is complex so it will take some time to develop. 

如果您想实现此功能，请提交拉取请求

if you want to make it yourself, make a pull request

另外，在这种情况下“网格大小”是什么意思？ 我很困惑

Also, what does "grid size" mean in this context? I'm confused

note: translation may be inaccurate, i do not know how to read chinese

**Comment by it7007** [comment]
1."grid size" can be understood as "square size"
2.I pulled the code, and I tried to use ChatGPT to modify the above functions, but since I am a JavaScrpit developer, Python is difficult for me, thank you for your reply.

**Comment by quasar098** [comment]
i have been meaning to add square size setting but i do not really have the time currently, i think i was going to add it but then didn't for some reason cant remember why
