### ISSUE TITLE
a question

### ISSUE THREAD

**Issue by dingus-bobingus** [quasar098/midi-playground#5]
for the song to work, there is a mainline, and there is the song itself. are they the same, and if they are different, how did you take the mainline from the song? (i wish to try it myself)

**Comment by quasar098** [comment]
for every file.mid, i make a file-mainlines.mid before playing it in front of others because lots of songs have background melody and such, and so without the mainlines file, every single note, melody and background, will be marked as a timestamp to bounce at, which leads to lots of unnecessary bounces. i use musescore 4 which is a free open source software for editing sheet music (it supports midi). i just make a "-mainlines" file that has only the melody, and you can open the existing mainlines file in musescore to see what i'm talking about. i highly recommend doing that
