### ISSUE TITLE
osu music

### ISSUE THREAD

**Issue by SamuelNathanGroupe7** [quasar098/midi-playground#57]
hello, is it possible to add custom music but .osu music? and if not, what means do you know of for converting an .mp3 file to .mid? thanks.

**Comment by quasar098** [comment]
mp3 files contain sound waves, but midi files contain instrument instructions like notes and timestamps. it is kind of hard to get the timestamps from an mp3 because ambient noise would cause false positives for timestamps, so i decided to use midi files for this project. there is not an easy way to convert mp3s to midis, but you can probably find what you are looking for online (search up "<song name> midi"). i was working on support for .osz (osu map files), but it isn't working so well.
