### ISSUE TITLE
(release version because i cant compile source code for some reason) The place where my mouse clicks register are VERY far off from where my mouse is

### ISSUE THREAD

**Issue by averageminecraftplayer** [quasar098/midi-playground#60]
https://github.com/quasar098/midi-playground/assets/123835086/2106e040-0fc1-46a3-91b3-7a2d5b00de2e

**Comment by a4aaron** [comment]
getting the same issue

**Comment by quasar098** [comment]
what is your monitor resolution

**Comment by quasar098** [comment]
change it to 1080p in windows settings if you can

also you dont need to compile source code, that is not how python works.

**Comment by a4aaron** [comment]
> change it to 1080p in windows settings if you can
> 
> also you dont need to compile source code, that is not how python works.

hey my monitor resolution is fixed at 1366x768 (im on a laptop) so i  cant change it to 1080p, also will it work, if you try to implement the old gui code into the new one because i was going through the commits and downloaded each  one and the one that still had the working 'mouse being over the gui box' was in '[2.0]
 quasar098
 committed
 8 months ago' or if that doesnt work, could you maybe make an update for this so people who have the same problem like me are able to use ur amazing masterpiece.

Thanks

**Comment by INGCGGGGG** [comment]
> change it to 1080p in windows settings if you can
> 
> also you dont need to compile source code, that is not how python works.

我的电脑是1920x1080的分辨率，但是我的设备有相同的问题，而且不能开始游戏。

**Comment by INGCGGGGG** [comment]
可以修改选择歌曲页面的“play”位置吗？比如移到中间，尽管这么做很丑，但我认为至少可以让有问题的玩家可以开始游戏。

**Comment by a4aaron** [comment]
> 可以修改选择歌曲页面的“play”位置吗？比如移到中间，尽管这么做很丑，但我认为至少可以让有问题的玩家可以开始游戏。

下载“提交”上面的代码 zip 内容，然后进入文件并找到“配置”，然后使用 Visual Studio Code 之类的东西打开文件，然后您应该看到屏幕宽度和屏幕长度将其更改为您的分辨率，然后保存文件，然后通过 cmd 提示符运行该文件，就像在“READ.ME”文件中一样

**Comment by it7007** [comment]
Why don't you guys try to fix these problems instead of letting the authors do the work for you?
Another thing: author I suspect that your code was exploited and then made into a program and uploaded to Steam for sale
!
![img](https://github.com/quasar098/midi-playground/assets/40188621/8c92ad42-2a8f-4c3d-ad42-d0f999ee5870)

**Comment by INGCGGGGG** [comment]
![51U3H0ZJ~ZTRG)_JZ6$I 5T](https://github.com/quasar098/midi-playground/assets/159463917/33e8deba-3926-45b9-8062-f2da3e4d3420)
是这个文件吗，修改之后运行了还是没有变，是只能在cmd中运行吗，游戏里面文字模糊，分辨率一定是有问题

**Comment by INGCGGGGG** [comment]
> > 可以修改选择歌曲页面的“play”位置吗？比如移到中间，尽管这么做很丑，但我认为至少可以让有问题的玩家可以开始游戏。
> 
> 下载“提交”上面的代码 zip 内容，然后进入文件并找到“配置”，然后使用 Visual Studio Code 之类的东西打开文件，然后您应该看到屏幕宽度和屏幕长度将其更改为您的分辨率，然后保存文件，然后通过 cmd 提示符运行该文件，就像在“READ.ME”文件中一样

重复进游戏几次居然好了,谢谢你,祝你农历新年快乐😊

**Comment by quasar098** [comment]
> > 可以修改选择歌曲页面的“play”位置吗？比如移到中间，尽管这么做很丑，但我认为至少可以让有问题的玩家可以开始游戏。
> 
> 下载“提交”上面的代码 zip 内容，然后进入文件并找到“配置”，然后使用 Visual Studio Code 之类的东西打开文件，然后您应该看到屏幕宽度和屏幕长度将其更改为您的分辨率，然后保存文件，然后通过 cmd 提示符运行该文件，就像在“READ.ME”文件中一样

some of the ui may be a little bit messed up, but if that works though, it works ig
