### ISSUE TITLE
Code is exploited

### ISSUE THREAD

**Issue by it7007** [quasar098/midi-playground#65]
Hi author, I suspect that your code is being used to make a game and upload it to Steam for sale.

link:https://store.steampowered.com/app/2720810/Tempo_Cube/

**Comment by it7007** [comment]
![Uploading img2.jpg…]()

**Comment by it7007** [comment]
![img](https://github.com/quasar098/midi-playground/assets/40188621/f4391594-4f0c-4481-828d-3b33eb1f365d)
![img2](https://github.com/quasar098/midi-playground/assets/40188621/e49951a1-4396-4213-8dad-2835ac5816a7)

**Comment by quasar098** [comment]
oh no!!! i hope they do not charge money for it

**Comment by quasar098** [comment]
maybe i can consult the open source community to see what i can do about this

if they do not provide the source code openly, it is a violation of the GPL3 license because of the new orange trail feature present on image 4

**Comment by quasar098** [comment]
i am most likely going to file a DMCA or some other copyright violation form on steam as it violates the GPL3 license

**Comment by apolloid** [comment]
![image](https://github.com/quasar098/midi-playground/assets/39253411/27e27d9b-51a4-454e-8969-4ca1999d11f3)
![image](https://github.com/quasar098/midi-playground/assets/39253411/e11d81cf-0d9e-4b3a-9df7-dfcbb7d38131)

Just saw this Upwork ads, your game is gaining traction!

**Comment by quasar098** [comment]
crazy! also, they link a project jdm tiktok, but have my code repo ??? but i was inspired by project jdm ?? i guess it is fine if they fix the code as long as they make a pr so it gets merged

**Comment by UniqueName12345** [comment]
Considering it's Steam we're dealing with, a store front that has had a track record of containing games that literally don't even contain anything, they likely wouldn't care

**Comment by quasar098** [comment]
> Considering it's Steam we're dealing with, a store front that has had a track record of containing games that literally don't even contain anything, they likely wouldn't care

hopefully this can be resolved without utilizing copyright law

**Comment by RabbitAaF** [comment]
well well, I am the developer of Tempo cube. Coded in c#, made with Unity. First vid uploaded a year ago. So, your repo is actually  a knock off, I don't mind you made your own repo, but stop pretending like you made it first.

**Comment by RabbitAaF** [comment]
After my game is released, if you repo was used by anyone to violate my rights. I will take my actions as well.

**Comment by quasar098** [comment]
> well well, I am the developer of Tempo cube. Coded in c#, made with Unity. First vid uploaded a year ago.

your earliest video i could find online on bilibili appeared to be uploaded after my first video on this software, which can be found [here](https://www.youtube.com/watch?v=QVFHQaE0FkA) (may 2023)

i made that video 8 months ago, which is before your first video, so your first video must be made less than 8 months ago

tiktok is not cooperating, so i cannot check that

> So, your repo is actually a knock off

again, the first evidence of my software existing dates prior to the first evidence of your software existing as far as i know

yes, it is not completely original idea, i was inspired by others who conceived this idea. they are very old channels, YOU must be a knock off too, so you cannot say anything about that

> I don't mind you releasing your own repo, but stop pretending like you made it first.

never have i said that i made this idea first

if you have done any research at all, i have been inspired by both Project JDM and Crazy Nutter 101 youtube channels, who originally created the idea (as far as i know). 

did you even read this entire github issue??? i already stated the below
![image](https://github.com/quasar098/midi-playground/assets/70716985/ca3bd4bd-ec18-4250-b4dc-abdd85f943aa)
ignorance may be bliss, but it sure is also a blunder in this case

anyways, i originally created this software to allow the open source community to overtake proprietary and potentially pay-to-use softwares. this essentially uses [clean room design](https://en.wikipedia.org/wiki/Clean_room_design), which means you effectively have no legal actions you can take, since our projects were developed separately

> After my game is released, if you repo was used by anyone to violate my rights. I will take my actions as well.

"violate my rights" ? wow

again, this software was made using clean room design, which bypasses your copyright on your software since this was made independently of your creation. i was not aware of you or your software's existence until recently anyways

i am not going to take this copyright issue too much further since i seems your software has some subtle differences compared to mine
i therefore do not believe your game is using mine "under the hood" / has any relation to mine.

however, i am going to push and advocate for the use of FOSS. this means attempting to encourage my software over yours because yours is proprietary (gross and morally dubious, in my opinion) and potentially for profit. especially if it is for profit, actually, then i will try my best to discourage the use of your closed source software

i highly encourage you to open source your game under some code license, because i will lessen my fighting against you, and because anyone can add features or help with development
